services:
  - type: web
    name: backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000 